# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.27)
{
  description = "Don Jorge - M3U playlist proxy service";

  inputs = {
    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";

    gomod2nix = {
      url = "github:nix-community/gomod2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      self,
      flake-schemas,
      nixpkgs,
      gomod2nix,
    }:
    let
      supportedSystems = [
        "x86_64-linux"
        "aarch64-linux"
      ];
      forEachSupportedSystem =
        f:
        nixpkgs.lib.genAttrs supportedSystems (
          system:
          f {
            pkgs = import nixpkgs { inherit system; };
          }
        );
    in
    {
      schemas = flake-schemas.schemas;

      packages = forEachSupportedSystem (
        { pkgs }:
        let
          gomod2nix-pkgs = gomod2nix.legacyPackages.${pkgs.stdenv.system};
          callPackage = pkgs.callPackage;
        in
        {
          don-jorge = callPackage self {
            inherit (gomod2nix-pkgs) buildGoApplication;
          };
          default = self.packages.${pkgs.stdenv.system}.don-jorge;
        }
      );

      nixosModules.default = import ./nixos { lib = nixpkgs.lib; };

      overlays.default = final: prev: {
        don-jorge = self.packages.${final.stdenv.system}.don-jorge;
      };

      devShells = forEachSupportedSystem (
        { pkgs }:
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              go
              nixd
            ];
          };
        }
      );
    };
}
